"use client";

import { useCallback, useEffect, useRef, useState, useTransition } from "react";
import { Bookmark, Droplets, Info, Loader2, MapPin, Sparkles, Sun, CloudRain, Snowflake } from "lucide-react";
import { generateOutfitsAction, getCachedOutfits, getSavedOutfits } from "@/app/outfits/actions";
import type { Outfit, OutfitRequest } from "@/lib/outfit-engine";
import { seasonFromTemp } from "@/lib/outfit-engine";
import type { Weather } from "@/lib/weather";
import { OCCASIONS, occasionLabel, type Occasion } from "@/types/wardrobe";
import { OutfitCard } from "@/components/outfits/outfit-card";
import { WeatherIcon } from "@/components/outfits/weather-icon";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";

const DEFAULT_TEMP = 68;

export function OutfitGenerator() {
  const [weather, setWeather] = useState<Weather | null>(null);
  const [weatherState, setWeatherState] = useState<"idle" | "loading" | "error">(
    "loading",
  );
  const [weatherError, setWeatherError] = useState<string | null>(null);

  const [temp, setTemp] = useState<number>(DEFAULT_TEMP);
  const [isRainy, setIsRainy] = useState(false);
  const [occasion, setOccasion] = useState<Occasion | null>(null);

  const [outfits, setOutfits] = useState<Outfit[] | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [emptyReason, setEmptyReason] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const [tab, setTab] = useState<"generate" | "saved">("generate");
  const [saved, setSaved] = useState<Outfit[]>([]);
  const [savedIds, setSavedIds] = useState<Set<string>>(new Set());

  const request: OutfitRequest = {
    current_temp_f: temp,
    occasion,
    is_rainy: isRainy,
  };

  const loadWeather = useCallback(() => {
    if (!("geolocation" in navigator)) {
      setWeatherState("error");
      setWeatherError("This browser cannot share your location.");
      return;
    }

    setWeatherState("loading");
    setWeatherError(null);

    navigator.geolocation.getCurrentPosition(
      async (position) => {
        try {
          const { latitude, longitude } = position.coords;
          const response = await fetch(
            `/api/weather?lat=${latitude}&lon=${longitude}`,
          );
          const payload = (await response.json()) as {
            weather?: Weather;
            error?: string;
          };
          if (!response.ok || !payload.weather) {
            throw new Error(payload.error ?? "Weather lookup failed.");
          }
          setWeather(payload.weather);
          setTemp(payload.weather.temp_f);
          setIsRainy(payload.weather.is_rainy);
          setWeatherState("idle");
        } catch (err) {
          setWeatherState("error");
          setWeatherError(
            err instanceof Error ? err.message : "Weather lookup failed.",
          );
        }
      },
      () => {
        setWeatherState("error");
        setWeatherError("Location denied — set the temperature by hand.");
      },
      { timeout: 10_000, maximumAge: 600_000 },
    );
  }, []);

  useEffect(() => {
    getSavedOutfits().then((res) => {
      if (res.ok) {
        setSaved(res.outfits);
        setSavedIds(new Set(res.outfits.map((o) => o.id)));
      }
    });
  }, []);

  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    getCachedOutfits({ current_temp_f: temp, occasion, is_rainy: isRainy }).then((cached) => {
      if (cached && cached.length > 0) setOutfits(cached);
    });
  }, [temp, occasion, isRainy]);

  useEffect(() => {
    if (weatherState === "loading") return;
    const t = setTimeout(() => { handleGenerate(); }, 450);
    return () => clearTimeout(t);
  }, [temp, occasion, isRainy, weatherState]);

  useEffect(() => {
    const timer = setTimeout(loadWeather, 0);
    return () => clearTimeout(timer);
  }, [loadWeather]);

  function handleGenerate() {
    setError(null);

    startTransition(async () => {
      const result = await generateOutfitsAction({
        current_temp_f: temp,
        occasion,
        is_rainy: isRainy,
      });

      if (!result.ok) {
        setError(result.error);
        setOutfits(null);
        return;
      }

      setOutfits(result.outfits);
      setNotice(result.notice);
      setEmptyReason(result.emptyReason);
    });
  }

  const season = seasonFromTemp(temp, isRainy);
  const seasonLabel = season === "summer" ? "Summer" : season === "winter" ? "Winter" : season === "rainy" ? "Rainy" : "All-season";
  const SeasonIcon = season === "summer" ? Sun : season === "winter" ? Snowflake : season === "rainy" ? CloudRain : Sun;

  return (
    <div className="flex flex-col gap-7 sm:gap-8">
      <div className="flex flex-wrap items-center gap-4 rounded-xl border border-border bg-card p-5">
        {weatherState === "loading" ? (
          <div className="flex items-center gap-3 text-sm text-muted-foreground">
            <Loader2 className="size-5 animate-spin" />
            Loading weather…
          </div>
        ) : weather ? (
          <>
            <WeatherIcon condition={weather.condition} className="size-10" />
            <div>
              <p className="text-3xl font-semibold leading-none">
                {weather.temp_f}°F
              </p>
              <p className="mt-1 text-sm text-muted-foreground">
                {weather.description} · feels {weather.feels_like_f}°F
              </p>
              <p className="mt-1 inline-flex items-center gap-1.5 rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">
                <SeasonIcon className="size-3.5" />
                {seasonLabel}{isRainy ? " · Rain" : ""}
              </p>
            </div>
          </>
        ) : (
          <div className="flex flex-1 flex-col gap-2">
            <p className="text-sm text-muted-foreground">
              {weatherError ?? "No weather yet."}
            </p>
            <Button
              variant="outline"
              size="sm"
              className="self-start"
              onClick={loadWeather}
            >
              <MapPin />
              Use my location
            </Button>
          </div>
        )}
      </div>

      <div className="flex flex-col gap-3">
        <div className="flex items-center justify-between">
          <Label>Occasion</Label>
          {pending && <span className="flex items-center gap-1.5 text-xs text-muted-foreground"><Loader2 className="size-3 animate-spin" />Updating…</span>}
        </div>
        <div className="flex flex-wrap gap-2">
          <OccasionChip active={occasion === null} onClick={() => setOccasion(null)}>Anything</OccasionChip>
          {OCCASIONS.map((value) => (
            <OccasionChip key={value} active={occasion === value} onClick={() => setOccasion(value)}>{occasionLabel(value)}</OccasionChip>
          ))}
        </div>
      </div>

      <div className="flex flex-wrap items-end gap-3">
        <div className="flex w-28 flex-col gap-1.5 sm:w-32">
          <Label htmlFor="temp">Temp °F</Label>
          <Input id="temp" type="number" value={temp} onChange={(e) => setTemp(Number(e.target.value))} />
        </div>
        <button type="button" onClick={() => setIsRainy((v) => !v)} className={cn("inline-flex h-11 flex-1 items-center justify-center gap-2 rounded-lg border px-4 text-sm font-medium active:scale-95 sm:h-10 sm:flex-none sm:rounded-md", isRainy ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card text-muted-foreground hover:bg-accent")}>
          <Droplets className="size-4" />Raining
        </button>
        <Button onClick={handleGenerate} disabled={pending} variant="outline" className="h-11 sm:h-10">
          <Sparkles className={cn(pending && "animate-spin")} />Shuffle
        </Button>
      </div>
      {error && <p className="text-sm text-destructive">{error}</p>}

      <Tabs value={tab} onValueChange={(v) => setTab(v as typeof tab)}>
        <TabsList>
          <TabsTrigger value="generate">Generated</TabsTrigger>
          <TabsTrigger value="saved">Saved ({saved.length})</TabsTrigger>
        </TabsList>
      </Tabs>

      {tab === "saved" ? (
        saved.length === 0 ? (
          <div className="rounded-xl border border-dashed border-border px-6 py-12 text-center">
            <Bookmark className="mx-auto size-6 text-muted-foreground" />
            <p className="mt-2 text-sm font-medium">Nothing saved yet</p>
            <p className="mx-auto mt-1 max-w-xs text-sm text-muted-foreground">
              Tap the bookmark on a look to keep it.
            </p>
          </div>
        ) : (
          <div className="grid gap-4 sm:grid-cols-2 sm:gap-5 lg:grid-cols-3">
            {saved.map((outfit, index) => (
              <OutfitCard
                key={outfit.id}
                outfit={outfit}
                rank={index + 1}
                request={request}
                saved
                onToggle={(id, nextSaved) => {
                  if (!nextSaved) {
                    setSaved((prev) => prev.filter((o) => o.id !== id));
                    setSavedIds((prev) => {
                      const n = new Set(prev);
                      n.delete(id);
                      return n;
                    });
                  }
                }}
              />
            ))}
          </div>
        )
      ) : (
        <>
          {outfits && outfits.length > 0 && notice && (
            <div className="flex gap-3 rounded-xl border border-border bg-muted/60 p-4">
              <Info className="mt-0.5 size-4 shrink-0" />
              <p className="text-sm leading-relaxed">{notice}</p>
            </div>
          )}

          {outfits && outfits.length === 0 && (
            <div className="rounded-xl border border-dashed border-border px-6 py-12 text-center">
              <p className="text-sm font-medium">No outfits yet</p>
              <p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">
                {emptyReason}
              </p>
            </div>
          )}

          {outfits && outfits.length > 0 && (
            <div className="grid gap-4 sm:grid-cols-2 sm:gap-5 lg:grid-cols-3">
              {outfits.map((outfit, index) => (
                <OutfitCard
                  key={outfit.id}
                  outfit={outfit}
                  rank={index + 1}
                  request={request}
                  saved={savedIds.has(outfit.id)}
                  onToggle={(id, nextSaved) => {
                    setSavedIds((prev) => {
                      const n = new Set(prev);
                      if (nextSaved) n.add(id);
                      else n.delete(id);
                      return n;
                    });
                    if (nextSaved) {
                      const found = outfits.find((o) => o.id === id);
                      if (found) setSaved((prev) => [found, ...prev.filter((o) => o.id !== id)]);
                    } else {
                      setSaved((prev) => prev.filter((o) => o.id !== id));
                    }
                  }}
                />
              ))}
            </div>
          )}

          {!outfits && !pending && (
            <div className="rounded-xl border border-dashed border-border px-6 py-12 text-center">
              <p className="text-sm font-medium">No looks yet</p>
              <p className="mx-auto mt-1 max-w-xs text-sm text-muted-foreground">
                Pick an occasion, or tap Shuffle.
              </p>
            </div>
          )}
        </>
      )}
    </div>
  );
}

function OccasionChip({
  active,
  onClick,
  children,
}: {
  active: boolean;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "rounded-full border px-4 py-2.5 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring active:scale-95 sm:py-1.5",
        active
          ? "border-primary bg-primary text-primary-foreground"
          : "border-border bg-card text-muted-foreground hover:bg-accent hover:text-foreground",
      )}
    >
      {children}
    </button>
  );
}
